#!/usr/bin/env python3
"""
wiki_seed.py — Generate wiki/_index.md and wiki/_index.json from all wiki pages.

Usage:
  python scripts/wiki_seed.py           # generate index files
  python scripts/wiki_seed.py --dry-run # print output, don't write files

Run after adding or editing wiki pages to update the search index.
The generated files are committed alongside the pages.

Output:
  wiki/_index.md   — human-readable table + excerpts (for Claude / accent-rag)
  wiki/_index.json — machine-readable JSON (for AccentOS browser UI / js/wiki.js)
"""

import json
import re
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(2)

WIKI_ROOT = Path(__file__).parent.parent / "wiki"
TYPED_DIRS = ["clusters", "sops", "adrs", "entities", "sources", "concepts"]
FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---\r?\n(.*)", re.DOTALL)

dry_run = "--dry-run" in sys.argv


def extract_page(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    m = FRONTMATTER_RE.match(text)
    if not m:
        print(f"  SKIP (no frontmatter): {path.relative_to(WIKI_ROOT.parent)}")
        return None

    try:
        fm = yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        print(f"  SKIP (bad YAML): {path.relative_to(WIKI_ROOT.parent)} — {e}")
        return None

    if not isinstance(fm, dict):
        return None

    body = m.group(2).strip()

    # Extract a clean 300-char excerpt: strip markdown headers + links, collapse whitespace
    excerpt_raw = re.sub(r"#+\s+", "", body)           # strip headers
    excerpt_raw = re.sub(r"\[([^\]]+)\]\([^\)]+\)", r"\1", excerpt_raw)  # strip links
    excerpt_raw = re.sub(r"[*_`>|]", "", excerpt_raw)  # strip formatting chars
    excerpt_raw = re.sub(r"\s+", " ", excerpt_raw).strip()
    excerpt = excerpt_raw[:300]

    # Build searchable text blob for TF-IDF index
    title = fm.get("title", "")
    tags = fm.get("tags") or []
    search_blob = f"{title} {' '.join(tags)} {body}".lower()

    return {
        "id": fm.get("id", path.stem),
        "title": title,
        "type": fm.get("type", "concept"),
        "status": fm.get("status", "draft"),
        "weight": fm.get("weight", 5) if isinstance(fm.get("weight"), int) else 5,
        "tags": tags if isinstance(tags, list) else [],
        "related": fm.get("related") or [],
        "created": str(fm.get("created", "")),
        "updated": str(fm.get("updated", "")),
        "path": str(path.relative_to(WIKI_ROOT.parent)),
        "excerpt": excerpt,
        "search_blob": search_blob,
    }


def score_page(page: dict, query_tokens: list[str]) -> float:
    """Simple TF-IDF approximation for a query against a page."""
    blob = page["search_blob"]
    blob_tokens = re.findall(r"\b\w+\b", blob)
    token_count = len(blob_tokens)
    if token_count == 0:
        return 0.0

    score = 0.0
    for token in query_tokens:
        tf = blob.count(token) / token_count
        # Boost tokens that appear in title or tags
        title_boost = 3.0 if token in page["title"].lower() else 1.0
        tag_boost = 2.0 if any(token in t.lower() for t in page["tags"]) else 1.0
        score += tf * title_boost * tag_boost

    # Apply weight multiplier
    score *= page["weight"] / 10.0
    return score


def search(pages: list[dict], query: str, top_k: int = 5) -> list[dict]:
    """Search pages for a query string. Returns top_k results."""
    stopwords = {"the", "a", "an", "is", "it", "in", "of", "to", "and", "or", "for",
                 "with", "on", "at", "by", "from", "that", "this", "be", "are", "was",
                 "how", "do", "i", "we", "my", "our", "can", "does", "what", "when"}
    tokens = [t for t in re.findall(r"\b\w+\b", query.lower()) if t not in stopwords]

    scored = [(score_page(p, tokens), p) for p in pages]
    scored.sort(key=lambda x: -x[0])
    return [p for _, p in scored[:top_k] if _ > 0]


def write_md_index(pages: list[dict], path: Path):
    lines = [
        "# AccentOS Wiki — Page Index",
        f"> Generated by wiki_seed.py on {date.today()}. {len(pages)} pages indexed.\n",
        "## Page table",
        "",
        "| id | title | type | weight | tags |",
        "|---|---|---|---|---|",
    ]
    for p in pages:
        tags = ", ".join(p["tags"]) if p["tags"] else "—"
        lines.append(f"| `{p['id']}` | {p['title']} | {p['type']} | {p['weight']} | {tags} |")

    lines += ["", "## Excerpts", ""]
    for p in pages:
        lines.append(f"### {p['title']}")
        lines.append(f"`{p['id']}` · {p['type']} · weight {p['weight']} · {p['status']}")
        if p["tags"]:
            lines.append(f"tags: {', '.join(p['tags'])}")
        if p["excerpt"]:
            # Wrap excerpt in blockquote
            lines.append(f"\n> {p['excerpt'][:200]}")
        lines.append(f"\nsource: `{p['path']}`")
        if p["related"]:
            lines.append(f"related: {', '.join(p['related'])}")
        lines.append("")

    content = "\n".join(lines)
    if dry_run:
        print(f"\n--- {path} ---\n{content[:800]}...\n")
    else:
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(WIKI_ROOT.parent)} ({len(pages)} pages)")


def write_json_index(pages: list[dict], path: Path):
    # Strip search_blob from JSON output (large, not needed in browser)
    export = [{k: v for k, v in p.items() if k != "search_blob"} for p in pages]
    content = json.dumps(export, indent=2, ensure_ascii=False)
    if dry_run:
        print(f"\n--- {path} (first 500 chars) ---\n{content[:500]}...\n")
    else:
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(WIKI_ROOT.parent)} ({len(pages)} pages)")


def run_self_test(pages: list[dict]):
    """Quick smoke test: verify 3 canonical queries return expected top-1 results."""
    tests = [
        ("add a new vendor onboarding", "sop-001-vendor-onboarding"),
        ("create a quote sales deal pipeline", "sop-002-quote-to-close"),
        ("inventory reorder low stock purchase order", "sop-003-inventory-reorder"),
        ("supabase tables schema migrations M-tasks RLS core tables", "supabase-source"),
        ("outdoor architectural lighting exterior fixture luminaire", "outdoor-architectural"),
        ("why did we choose supabase over firebase architecture decision", "adr-002-supabase-backend"),
        ("pendant chandelier indoor decorative luminaire fixture residential", "indoor-decorative"),
        ("warehouse employee role inventory deliveries labels access", "emp-warehouse"),
    ]
    print("\nSelf-test (top-1 recall):")
    passed = 0
    for query, expected_id in tests:
        results = search(pages, query, top_k=3)
        ids = [r["id"] for r in results]
        ok = expected_id in ids[:1]
        status = "✓" if ok else f"✗ (got {ids[:1]})"
        print(f"  {status}  '{query[:40]}' → {expected_id}")
        if ok:
            passed += 1
    print(f"\nSelf-test: {passed}/{len(tests)} passed")


def main():
    if not WIKI_ROOT.exists():
        print(f"ERROR: wiki directory not found at {WIKI_ROOT}")
        sys.exit(2)

    print(f"WIKI SEED — scanning {WIKI_ROOT}/")

    pages = []
    for dir_name in TYPED_DIRS:
        dir_path = WIKI_ROOT / dir_name
        if not dir_path.exists():
            continue
        for md_file in sorted(dir_path.glob("*.md")):
            page = extract_page(md_file)
            if page:
                pages.append(page)

    # Sort: weight desc, then type, then title
    pages.sort(key=lambda p: (-p["weight"], p["type"], p["title"]))

    print(f"Found {len(pages)} pages across {TYPED_DIRS}")

    write_md_index(pages, WIKI_ROOT / "_index.md")
    write_json_index(pages, WIKI_ROOT / "_index.json")

    run_self_test(pages)

    print("\nDone. Commit wiki/_index.md and wiki/_index.json.")


if __name__ == "__main__":
    main()
